<?php $pageTitle="Development — Building the Future | Pulisanbay"; $pageDescription="Follow the progress of KEK Likupang's infrastructure development — from road improvements to the visionary International Marina at Pulisanbay."; $navStyle=""; ?>
<!DOCTYPE html><html lang="en"><head><?php include __DIR__.'/../includes/head.php'; ?></head><body>
<?php include __DIR__.'/../includes/navbar.php'; ?>
<section class="hero"><div class="hero-bg" style="background-image:url('../assets/images/hero-development.png')"></div><div class="hero-content"><h1>Development</h1><p>Transforming a vision into reality — building world-class infrastructure that harmonizes with the natural landscape of Pulisan Bay.</p></div><div class="hero-scroll-indicator"><span></span></div></section>

<section class="section-lg section-bg-white"><div class="container"><div class="section-header reveal"><span class="section-label">Progress Update</span><h2>Infrastructure Development</h2><p>The KEK Likupang Special Economic Zone is advancing steadily — with careful attention to environmental integration at every stage.</p></div><div class="grid-2 reveal">
  <div class="card"><div class="card-body" style="padding:2.5rem;"><div style="display:flex;align-items:center;gap:12px;margin-bottom:1.25rem;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,var(--oceanic-turquoise),var(--deep-sea));display:flex;align-items:center;justify-content:center;"><i class="fas fa-road" style="color:var(--white);"></i></div><h3 style="margin:0;">Road Network</h3></div><p style="color:var(--slate);">Major improvements to the regional road network connecting Sam Ratulangi Airport to the KEK Likupang area.</p><div style="margin-top:1.5rem;background:var(--earthy-sand);border-radius:8px;padding:1rem;"><div style="display:flex;justify-content:space-between;font-size:0.85rem;color:var(--slate);margin-bottom:0.5rem;"><span>Progress</span><span style="font-weight:600;color:var(--oceanic-turquoise);">75%</span></div><div style="height:8px;background:#E2E8F0;border-radius:4px;overflow:hidden;"><div style="height:100%;width:75%;background:linear-gradient(90deg,var(--oceanic-turquoise),var(--deep-sea));border-radius:4px;"></div></div></div></div></div>
  <div class="card reveal-delay-1"><div class="card-body" style="padding:2.5rem;"><div style="display:flex;align-items:center;gap:12px;margin-bottom:1.25rem;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,var(--forest-green),#22C55E);display:flex;align-items:center;justify-content:center;"><i class="fas fa-bolt" style="color:var(--white);"></i></div><h3 style="margin:0;">Utilities</h3></div><p style="color:var(--slate);">Comprehensive utilities infrastructure including reliable electricity, clean water, and telecommunications.</p><div style="margin-top:1.5rem;background:var(--earthy-sand);border-radius:8px;padding:1rem;"><div style="display:flex;justify-content:space-between;font-size:0.85rem;color:var(--slate);margin-bottom:0.5rem;"><span>Progress</span><span style="font-weight:600;color:var(--forest-green);">60%</span></div><div style="height:8px;background:#E2E8F0;border-radius:4px;overflow:hidden;"><div style="height:100%;width:60%;background:linear-gradient(90deg,var(--forest-green),#22C55E);border-radius:4px;"></div></div></div></div></div>
  <div class="card"><div class="card-body" style="padding:2.5rem;"><div style="display:flex;align-items:center;gap:12px;margin-bottom:1.25rem;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,var(--savanna-gold),#B8860B);display:flex;align-items:center;justify-content:center;"><i class="fas fa-building" style="color:var(--white);"></i></div><h3 style="margin:0;">Resort Facilities</h3></div><p style="color:var(--slate);">Construction of premium resort facilities including The Pulisan accommodation, dining venues, and wellness center.</p><div style="margin-top:1.5rem;background:var(--earthy-sand);border-radius:8px;padding:1rem;"><div style="display:flex;justify-content:space-between;font-size:0.85rem;color:var(--slate);margin-bottom:0.5rem;"><span>Progress</span><span style="font-weight:600;color:var(--savanna-gold);">45%</span></div><div style="height:8px;background:#E2E8F0;border-radius:4px;overflow:hidden;"><div style="height:100%;width:45%;background:linear-gradient(90deg,var(--savanna-gold),#B8860B);border-radius:4px;"></div></div></div></div></div>
  <div class="card reveal-delay-1"><div class="card-body" style="padding:2.5rem;"><div style="display:flex;align-items:center;gap:12px;margin-bottom:1.25rem;"><div style="width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#7C3AED,#A855F7);display:flex;align-items:center;justify-content:center;"><i class="fas fa-tree" style="color:var(--white);"></i></div><h3 style="margin:0;">Conservation Zones</h3></div><p style="color:var(--slate);">Formal delineation and protection of conservation zones, wildlife corridors, and marine protected areas.</p><div style="margin-top:1.5rem;background:var(--earthy-sand);border-radius:8px;padding:1rem;"><div style="display:flex;justify-content:space-between;font-size:0.85rem;color:var(--slate);margin-bottom:0.5rem;"><span>Progress</span><span style="font-weight:600;color:#7C3AED;">85%</span></div><div style="height:8px;background:#E2E8F0;border-radius:4px;overflow:hidden;"><div style="height:100%;width:85%;background:linear-gradient(90deg,#7C3AED,#A855F7);border-radius:4px;"></div></div></div></div></div>
</div></div></section>

<section class="section-lg section-bg-dark"><div class="container"><div class="section-header reveal"><span class="section-label" style="color:var(--savanna-gold);">Looking Ahead</span><h2>Long-Term Vision</h2><p>Beyond what stands today lies a bold vision for the future.</p></div><div class="grid-3 reveal"><div class="pillar-card"><div class="pillar-icon" style="background:linear-gradient(135deg,var(--oceanic-turquoise),var(--deep-sea));"><i class="fas fa-ship"></i></div><h3>International Marina</h3><p>A state-of-the-art marina welcoming international yachts and vessels.</p></div><div class="pillar-card reveal-delay-1"><div class="pillar-icon" style="background:linear-gradient(135deg,var(--forest-green),#22C55E);"><i class="fas fa-horse"></i></div><h3>Sports &amp; Equestrian</h3><p>An integrated sports complex with equestrian facilities and fitness centers.</p></div><div class="pillar-card reveal-delay-2"><div class="pillar-icon" style="background:linear-gradient(135deg,var(--savanna-gold),#B8860B);"><i class="fas fa-people-roof"></i></div><h3>MICE Convention Center</h3><p>International-standard convention center for global events.</p></div></div></div></section>

<?php $ctaTitle="Watch This Space"; $ctaText="The future of Pulisanbay is being built today. Stay connected for the latest updates."; $ctaLabel="Stay Updated"; include __DIR__.'/../includes/cta-banner.php'; ?>
<?php include __DIR__.'/../includes/footer.php'; ?>
<script src="../assets/js/main.js"></script>
</body></html>
