<?php $pageTitle="Gastronomy — Sea-to-Table Dining | Pulisanbay"; $pageDescription="Savor the culinary soul of North Sulawesi at Pulisanbay. Sea-to-table dining, iconic local dishes, and flexible dietary accommodations."; $navStyle=""; ?>
<!DOCTYPE html><html lang="en"><head><?php include __DIR__.'/../includes/head.php'; ?></head><body>
<?php include __DIR__.'/../includes/navbar.php'; ?>
<section class="hero"><div class="hero-bg" style="background-image:url('../assets/images/hero-gastronomy.png')"></div><div class="hero-content"><h1>Gastronomy</h1><p>Where the ocean's harvest meets the hands of local artisans — every plate tells a story of the land, the sea, and the people who call this place home.</p></div><div class="hero-scroll-indicator"><span></span></div></section>

<section class="section-lg section-bg-white"><div class="container"><div class="section-header reveal"><span class="section-label">Culinary Icons</span><h2>Flavors of North Sulawesi</h2><p>Discover the bold, aromatic, and unforgettable flavors that define Minahasa cuisine.</p></div><div class="grid-3 reveal"><div class="card"><div class="card-img-wrapper"><img src="../assets/images/hero-gastronomy.png" alt="Local Cuisine" class="card-img"></div><div class="card-body"><h3>Tinutuan</h3><p>The beloved Manadonese porridge — a hearty blend of pumpkin, corn, sweet potato, and leafy greens, seasoned with local spices.</p></div></div><div class="card reveal-delay-1"><div class="card-img-wrapper"><img src="../assets/images/hero-gastronomy.png" alt="Grilled Fish" class="card-img"></div><div class="card-body"><h3>Ikan Bakar Rica</h3><p>Fresh-caught fish grilled over coconut husk charcoal and dressed in fiery rica-rica sambal.</p></div></div><div class="card reveal-delay-2"><div class="card-img-wrapper"><img src="../assets/images/hero-gastronomy.png" alt="Dessert" class="card-img"></div><div class="card-body"><h3>Klapertaart</h3><p>A Manadonese coconut custard tart — the region's most beloved dessert.</p></div></div></div></div></section>

<section class="section-lg section-bg-sand"><div class="container"><div class="split-section"><div class="reveal"><span class="section-label">Our Philosophy</span><h2>Sea-to-Table</h2><p style="color:var(--slate);margin-bottom:1.5rem;">At Pulisanbay, the distance between the ocean and your plate is measured not in miles, but in hours. Our chefs work directly with local fishermen who harvest sustainably from the waters of Pulisan Bay.</p><p style="color:var(--slate);margin-bottom:1.5rem;">This isn't just a culinary concept — it's a commitment. By partnering with local fishing communities, we ensure that traditional fishing practices are sustained and fishermen earn fair wages.</p><p style="color:var(--slate);margin-bottom:2rem;">From the morning's catch to the evening's masterpiece — experience the purest expression of coastal cuisine, enhanced with herbs and spices grown in our own resort gardens.</p></div><div class="reveal reveal-delay-2"><div class="img-rounded" style="box-shadow:var(--shadow-lg);"><img src="../assets/images/hero-gastronomy.png" alt="Sea to Table" class="img-cover" style="height:480px;"></div></div></div></div></section>

<section class="section-lg section-bg-white"><div class="container"><div class="section-header reveal"><span class="section-label">Tailored for You</span><h2>Dietary Accommodations</h2><p>We believe every guest deserves an exceptional dining experience, regardless of dietary needs.</p></div><div class="grid-4 grid-4-dense reveal"><div class="pillar-card"><div class="pillar-icon" style="background:linear-gradient(135deg,var(--forest-green),#22C55E);"><i class="fas fa-leaf"></i></div><h3>Vegetarian &amp; Vegan</h3><p>Full vegetarian and vegan menus crafted with the same creativity and care.</p></div><div class="pillar-card reveal-delay-1"><div class="pillar-icon" style="background:linear-gradient(135deg,var(--savanna-gold),#B8860B);"><i class="fas fa-wheat-awn-circle-exclamation"></i></div><h3>Gluten-Free</h3><p>Gluten-free options available across all meals.</p></div><div class="pillar-card reveal-delay-2"><div class="pillar-icon" style="background:linear-gradient(135deg,var(--oceanic-turquoise),var(--deep-sea));"><i class="fas fa-triangle-exclamation"></i></div><h3>Allergy-Aware</h3><p>Detailed allergen information available. Our chefs can adapt any dish.</p></div><div class="pillar-card reveal-delay-3"><div class="pillar-icon" style="background:linear-gradient(135deg,#DC2626,#F97316);"><i class="fas fa-star-and-crescent"></i></div><h3>Halal Options</h3><p>Halal-prepared meals available upon advance request.</p></div></div></div></section>

<?php $ctaTitle="Taste the Story of Pulisanbay"; $ctaText="From dawn's first coffee to a candlelit dinner beneath the stars — every meal is a memory waiting to be savored."; $ctaLabel="Reserve a Dining Experience"; $ctaGradient="linear-gradient(135deg,var(--deep-sea),var(--deep-sea-dark))"; include __DIR__.'/../includes/cta-banner.php'; ?>
<?php include __DIR__.'/../includes/footer.php'; ?>
<script src="../assets/js/main.js"></script>
</body></html>
