name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main
      - feature/1-implement-ci-cd
  workflow_dispatch:

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      # Install Dependencies & Run Build Script
      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      # Upload to cPanel Shared Hosting via SFTP
      - name: Deploy to cPanel
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          ssh_private_key: ${{ secrets.SFTP_SSH_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          remote_path: "./ci_cd_test/"
          delete_remote_files: false
